version: 2

jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - checkout
      - run: pwd
      - run: ls
      - restore_cache:
          keys:
            - 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
            - 'v2-deps-{{ .Branch }}-'
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - tmp
  test_account_settings:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/account_settings
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/account_settings/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_at_mentions:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/at_mentions
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/at_mentions/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_channel:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/channel
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/channel/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_email:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/email
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/email/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_emoji:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/emoji
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/emoji/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_enterprise:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/enterprise
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/enterprise/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_integrations:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/integrations
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/integrations/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
            CYPRESS_webhookBaseUrl: http://localhost:3000
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_interactive_dialog:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/interactive_dialog
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/interactive_dialog/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
            CYPRESS_webhookBaseUrl: http://localhost:3000
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_interactive_menu:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/interactive_menu
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/interactive_menu/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
            CYPRESS_webhookBaseUrl: http://localhost:3000
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_login:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/login
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/login/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_markdown:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/markdown
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/markdown/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_messaging:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/messaging
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/messaging/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_multi_team:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/multi_team
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/multi_team/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_onboarding:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/onboarding
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/onboarding/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_plugins:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/plugins
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/plugins/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_post_header:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/post_header
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/post_header/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_search:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/search
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/search/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_signin_authentication:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/signin_authentication
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/signin_authentication/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_system_console:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/system_console
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/system_console/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_team:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/team
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/team/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test_widgets:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration/widgets
      - run:
          name: Running cypress tests
          command: $(npm bin)/cypress run --spec 'cypress/integration/widgets/**/*'
          environment:
            CYPRESS_baseUrl: https://cypress.test.mattermost.com
            CYPRESS_storybookUrl: https://alpha-storybook.devops.mattermost.com/master/index.html
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_plugins:
          requires:
            - build
      - test_team:
          requires:
            - test_plugins
      - test_onboarding:
          requires:
            - test_team
      - test_signin_authentication:
          requires:
            - test_onboarding
      - test_channel:
          requires:
            - test_signin_authentication
      - test_markdown:
          requires:
            - test_channel
      - test_messaging:
          requires:
            - test_markdown
      - test_account_settings:
          requires:
            - test_messaging
      - test_search:
          requires:
            - test_account_settings
      - test_at_mentions:
          requires:
            - test_search
      - test_system_console:
          requires:
            - test_at_mentions
      - test_email:
          requires:
            - test_system_console
      - test_emoji:
          requires:
            - test_email
      - test_integrations:
          requires:
            - test_emoji
      - test_login:
          requires:
            - test_integrations
      - test_post_header:
          requires:
            - test_login
      - test_enterprise:
          requires:
            - test_post_header
      - test_interactive_dialog:
          requires:
            - test_enterprise
      - test_interactive_menu:
          requires:
            - test_interactive_dialog
      - test_multi_team:
          requires:
            - test_interactive_menu
      - test_widgets:
          requires:
            - test_multi_team
